# Hardware acceleration for Intel UHD 620
LIBVA_DRIVER_NAME=iHD
VDPAU_DRIVER=va_gl

# Intel GPU optimizations
INTEL_DEBUG=noccs
ANV_QUEUE_THREAD_DISABLE=1

# Wayland
MOZ_ENABLE_WAYLAND=1
MOZ_DISABLE_RDD_SANDBOX=1
QT_QPA_PLATFORM=wayland;xcb
