#! /bin/sh

#  ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓ ██▀███   ▄████▄
# ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█
# ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄
# ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
# ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
# ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
# ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  ░▒ ░ ▒░  ░  ▒
#  ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     ░░   ░ ░
#  ░            ░               ░           ░      ░     ░ ░
#       ░                                                ░

# bspc monitor -d term web files video
intern=eDP-1
extern=DP-2

if xrandr | grep -w "$extern connected"; then
    xrandr --newmode "1680x1050_60.00"  147.14  1680 1784 1968 2256  1050 1051 1054 1087  -HSync +Vsync
    xrandr --addmode $extern 1680x1050_60.00
    xrandr --output $extern --mode 1680x1050_60.00
    xrandr --output $intern  --rotate normal --output $extern --primary --rotate normal --above $extern --pos 0x0
    bspc monitor $extern -d 1 2
    bspc monitor $intern -d 3 4
else
    bspc monitor $intern -d 1 2 3 4
fi

bspc config border_width         2
bspc config window_gap          25
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20

bspc rule -a kitty			    desktop='^1' follow=on focus=on
bspc rule -a qutebrowser		desktop='^2' follow=on
bspc rule -a Pcmanfm			desktop='^3' follow=on
bspc rule -a Lxappearence		desktop='^4' follow=on

bspc rule -a Vimiv				state=floating follow=on
bspc rule -a mpv				state=floating follow=on
bspc rule -a feh				state=floating follow=on
bspc rule -a URxvt				state=floating follow=on

bspc rule -a Tilix:quake        state=floating

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true


# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$fg"
bspc config presel_feedback_color "$color7"

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# execute some nice programs on startup.
. "${HOME}/.config/bspwm/autostart"
